title: TradeNet Portfolio
description: Manage your earnings easily
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - POLICY.md
  - README.md
  - TOS.md
